# Generated by Django 2.0.1 on 2018-02-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_by',
            new_name='created_by',
        ),
    ]
